/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package design.admin;

import javax.swing.*;

import logic.company_members.Admin;

import java.awt.*;
import java.lang.NumberFormatException;

/**
 *
 * @author Administrador
 */
public class AdminLoans extends javax.swing.JFrame {

    /**
     * Creates new form AdminLoans
     */
    public AdminLoans() {
        initComponents();
        JFormattedTextField tf = ((JSpinner.DefaultEditor) spinnerAuthorization.getEditor()).getTextField();
        tf.setEditable(false);
        showData();
        
        
    }
    
    private void showData(){
        insertValueToLend.setText(String.valueOf(Admin.getMaximumAmountToLend()));
        insertValuePerClient.setText(String.valueOf(Admin.getMaximumToLendPerClient()));
        spinnerAuthorization.setValue(Admin.getAuthDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Variables declaration - do not modify//GEN-BEGIN:variables
        org.edisoncor.gui.button.ButtonAeroRight buttonAeroRight1 = new org.edisoncor.gui.button.ButtonAeroRight();
        org.edisoncor.gui.panel.Panel panel1 = new org.edisoncor.gui.panel.Panel();
        org.edisoncor.gui.panel.PanelCurves panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        org.edisoncor.gui.panel.PanelImage panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel textAuthorization = new javax.swing.JLabel();
        javax.swing.JLabel textValueToLend = new javax.swing.JLabel();
        javax.swing.JLabel textValuePerClient = new javax.swing.JLabel();
        spinnerAuthorization = new javax.swing.JSpinner();
        insertValuePerClient = new javax.swing.JTextField();
        insertValueToLend = new javax.swing.JTextField();
        org.edisoncor.gui.panel.PanelImage panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        buttonConfirm = new org.edisoncor.gui.button.ButtonIpod();
        buttonEdit = new org.edisoncor.gui.button.ButtonIpod();
        org.edisoncor.gui.button.ButtonIpod buttonBack = new org.edisoncor.gui.button.ButtonIpod();
        org.edisoncor.gui.label.LabelCustom textConfigLoans = new org.edisoncor.gui.label.LabelCustom();

        buttonAeroRight1.setText("buttonAeroRight1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setColorPrimario(new java.awt.Color(153, 153, 255));
        panel1.setColorSecundario(new java.awt.Color(255, 255, 255));

        panelImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12)); // NOI18N

        textAuthorization.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12)); // NOI18N
        textAuthorization.setText("Maximum loan authorization day:");

        textValueToLend.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12)); // NOI18N
        textValueToLend.setText("Maximum value to lend:");

        textValuePerClient.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12)); // NOI18N
        textValuePerClient.setText("Maximum value to lend per client:");

        spinnerAuthorization.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));
        spinnerAuthorization.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spinnerAuthorization.setEnabled(false);
        spinnerAuthorization.setName(""); // NOI18N
        spinnerAuthorization.setValue(1);

        insertValuePerClient.setEnabled(false);

        insertValueToLend.setEnabled(false);

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textValuePerClient)
                    .addComponent(textValueToLend)
                    .addComponent(textAuthorization, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insertValuePerClient)
                    .addComponent(spinnerAuthorization)
                    .addComponent(insertValueToLend, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textValueToLend, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertValueToLend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textValuePerClient, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertValuePerClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAuthorization, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerAuthorization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelImage2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/confirm.png"))); // NOI18N
        buttonConfirm.setText("Confirm");
        buttonConfirm.setAnimacion(false);
        buttonConfirm.setEnabled(false);
        buttonConfirm.addActionListener(evt -> buttonConfirmActionPerformed());

        buttonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        buttonEdit.setText("Edit");
        buttonEdit.setAnimacion(false);
        buttonEdit.addActionListener(evt -> buttonEditActionPerformed());

        buttonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.jpg"))); // NOI18N
        buttonBack.setText("Back");
        buttonBack.setAnimacion(false);
        buttonBack.addActionListener(evt -> buttonBackActionPerformed());

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(buttonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textConfigLoans.setBackground(new java.awt.Color(102, 102, 102));
        textConfigLoans.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textConfigLoans.setText("Config Loans");
        textConfigLoans.setColorDeSegundoBorde(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelCurves1Layout = new javax.swing.GroupLayout(panelCurves1);
        panelCurves1.setLayout(panelCurves1Layout);
        panelCurves1Layout.setHorizontalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textConfigLoans, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCurves1Layout.setVerticalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textConfigLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed() {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        AdminInterface AdminInterface1 = new AdminInterface();
        this.setVisible(false);
        AdminInterface1.setVisible(true);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonEditActionPerformed() {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
        insertValueToLend.setEnabled(true);
        insertValuePerClient.setEnabled(true);
        spinnerAuthorization.setEnabled(true);
        buttonEdit.setEnabled(false);
        buttonConfirm.setEnabled(true);
        
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonConfirmActionPerformed() {//GEN-FIRST:event_buttonConfirmActionPerformed
        // TODO add your handling code here:
        int cont = 0;
        String errors = "";
        double totalValue = 0, valuePerClient = 0;
        
        try {
            totalValue = Double.parseDouble(insertValueToLend.getText());
        } catch (NumberFormatException e) {
            errors += "- You cant use letters for the maximum value to lend or leave it blank! \n";
            cont++;
        }
        
        try {
           valuePerClient = Double.parseDouble(insertValuePerClient.getText());
        } catch (NumberFormatException e) {
            errors += "- You cant use letters for the maximum value to lend per client or leave it blank! \n";
            cont++;
        }
            
        try
        {
         Admin.changeMaximumAmountToLend(Double.parseDouble(insertValueToLend.getText()));
         Admin.changeMaximumToLendPerClient(Double.parseDouble(insertValuePerClient.getText()));
         Admin.changeAuthDate((int) spinnerAuthorization.getValue()); 
        }
         catch (NumberFormatException e)
         {
            cont++;
         }
        
        
        if (cont == 0)
        
        { 
            if (totalValue <= valuePerClient) {
                  errors += "- The value to lend to clients cannot be greater or equal than the total!  \n";
                  cont++;
            } 
            
            if (cont == 0)
            {
                JOptionPane.showMessageDialog(null, "Data updated!", "Success!", JOptionPane.INFORMATION_MESSAGE);
                insertValueToLend.setEnabled(false);
                insertValuePerClient.setEnabled(false);
                spinnerAuthorization.setEnabled(false);
                buttonEdit.setEnabled(true);
                buttonConfirm.setEnabled(false);  } 
            
            else {  JOptionPane.showMessageDialog(null, errors, "ERROR!", JOptionPane.ERROR_MESSAGE);   }
            
        }
        
        else {  JOptionPane.showMessageDialog(null, errors, "ERROR!", JOptionPane.ERROR_MESSAGE);   }
            
    }//GEN-LAST:event_buttonConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLoans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminLoans().setVisible(true));
    }

    private org.edisoncor.gui.button.ButtonIpod buttonConfirm;
    private org.edisoncor.gui.button.ButtonIpod buttonEdit;
    private javax.swing.JTextField insertValuePerClient;
    private javax.swing.JTextField insertValueToLend;
    private javax.swing.JSpinner spinnerAuthorization;
    // End of variables declaration//GEN-END:variables

}
